version: "3"
services:
  go:
    container_name: koukaten2022_go
    build:
      context: ./backend/build/app
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    env_file:
      - ./backend/build/db/.env
    volumes:
      - type: bind
        source: .
        target: /go/app
    ports:
      - 8080:8080
    depends_on:
      - "mysql"
    

  mysql:
    #image: mysql:8.0
    container_name: koukaten2022_DB
    build:
      context: ./backend/build/db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./backend/build/db/init:/docker-entrypoint-initdb.d
      # - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      # MYSQL_DATABASE: koukaten2022_DB
      # MYSQL_USER: koukaten2022
      # MYSQL_PASSWORD: password
      # TZ: 'Asia/Tokyo'

# volumes:
#   data:
#     driver: local