version: "3"
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - "mysql"
    

  mysql:
    container_name: koukaten2022_DB
    build: ./Docker/mysql
    ports:
      - "3306:3306"
    volumes:
      - ./Docker/mysql/init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
      # - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: koukaten2022_DB
      MYSQL_USER: koukaten2022
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'

volumes:
  mysql-data:
    driver: local