version: "3"
services:
  mysql:
    container_name: koukaten2022_mysql
    build: ./mysql
    image: koukaten_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: koukaten2022_DB

  neo4j:
    container_name: koukaten2022_neo4j
    build: ./neo4j
    image: koukaten_neo4j
    ports:
      - "57474:7474"
      - "57687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/conf:/conf
      - ./neo4j/import:/import
      - ./neo4j/script:/script
    environment:
    - NEO4J_AUTH=neo4j/password

    - NEO4J_dbms_memory_heap_max__size=1G
    - NEO4J_dbms_memory_heap_initial__size=1G
    - NEO4J_dbms_memory_pagecache_size=113725k
    - NEO4J_dbms_memory.off_heap.max_size=625m

    - EXTENSION_SCRIPT=/script/import_data.sh